apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: video-extractor
type: Opaque
data:
  # Default Redis (no password) - base64 encoded empty string
  redis-password: ""
  redis-username: ""
stringData:
  # Alternative: plain text (K8s will base64 encode)
  redis-host: "redis-service"
  redis-port: "6379"